apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-frontend
spec:
  selector:
    matchLabels:
      app: project-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: project-frontend
    spec:
      containers:
      - name: project-frontend
        image: docker.io/shradhaagarwal810/project-frontend
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_URL
          value: http://project-backend.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: project-frontend
spec:
  selector:
    app: project-frontend
  ports:
  - port: 8000
    targetPort: 8000
